agregando htaccess

diff --git a/.github/workflows/deploy-qa.yml b/.github/workflows/deploy-qa.yml
--- a/.github/workflows/deploy-qa.yml
+++ b/.github/workflows/deploy-qa.yml
@@ -32,5 +32,8 @@ jobs:
             echo "Ejecutando npm run build -- --configuration=qa"
             npm run build -- --configuration=qa || { echo "Error: Falló npm run build"; exit 1; }
 
+            echo "Copiando .htaccess al directorio de distribución..."
+            cp .htaccess dist/caracterizacion-front/browser/ || { echo "Error: No se pudo copiar .htaccess"; exit 1; }
+
             echo "Frontend desplegado correctamente en qa."
           EOF
